FROM ubuntu:16.04
MAINTAINER Manika Kapoor version: 0.1
RUN apt-get update
RUN apt-get install python2.7 python-pip gcc python2.7-dev git-core -y --force-yes
ADD id_rsa config /root/.ssh/
ADD id_rsa /root/.ssh/id_rsa
RUN git clone git@github.com:manika1511/CMPE281.git ~/community
WORKDIR /root/community
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["app.py"]
